export const CLUES = [
  {
    id: 1,
    question: "I have keys but no locks. I have space but no room. You can enter, but can't go inside. What am I?",
    hint: "You type on me every day 🤔",
    answer: "keyboard",
    rewardTitle: "Memory Unlocked: The Beginning 🌟",
    rewardText: "Remember when this whole adventure started? Just like solving your first clue, every great story has a first page. You've always been the kind of person who figures things out — one step at a time, with style.",
    icon: "🔑",
    nodePos: { x: 10, y: 30 },
    color: "#FFD700",
  },
  {
    id: 2,
    question: "The more you take, the more you leave behind. What am I?",
    hint: "Think about walking somewhere 👣",
    answer: "footsteps",
    rewardTitle: "Memory Unlocked: The Journey 🚶‍♀️",
    rewardText: "Every step you've taken has led here. The paths you've chosen, the places you've gone, the moments you've created — they all matter. And they've all been spectacular, even the detours.",
    icon: "👣",
    nodePos: { x: 30, y: 15 },
    color: "#9B59B6",
  },
  {
    id: 3,
    question: "I speak without a mouth and hear without ears. I have no body, but I come alive with the wind. What am I?",
    hint: "Mountains know me well 🏔️",
    answer: "echo",
    rewardTitle: "Memory Unlocked: The Laughs 😂",
    rewardText: "Some things echo forever — your laugh, your energy, the way you make every room brighter just by walking in. The good times have a way of bouncing back, again and again.",
    icon: "🌊",
    nodePos: { x: 50, y: 50 },
    color: "#E74C3C",
  },
  {
    id: 4,
    question: "I have cities but no houses live there. I have mountains but no trees grow there. I have water but no fish swim there. What am I?",
    hint: "You've probably stared at one planning a trip 🗺️",
    answer: "map",
    rewardTitle: "Memory Unlocked: The Adventures 🌍",
    rewardText: "You've always had a map in your heart — a sense of where you're going even when the road isn't clear. Here's to every adventure, every detour, every destination still to come.",
    icon: "🗺️",
    nodePos: { x: 70, y: 25 },
    color: "#1ABC9C",
  },
  {
    id: 5,
    question: "What can you catch but not throw?",
    hint: "Happens when someone sneezes near you 🤧",
    answer: "cold",
    rewardTitle: "Memory Unlocked: The Future ✨",
    rewardText: "The greatest treasure isn't in any vault. It's in the years ahead — full of moments not yet lived, laughter not yet laughed, and adventures not yet had. And you, Your Majesty, are ready for all of them.",
    icon: "❄️",
    nodePos: { x: 90, y: 45 },
    color: "#F39C12",
  },
];
